### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ArtemZakhar**
Hi)

[DEMO LINK](https://ArtemZakhar.github.io/react_carousel/)

I have no patience with this task anymore))

When I try to solve one thing - another becomes broken)

All below don't work: 
1. setTimeout work inappropriately;
2. infinite prop doesn't work (in the first edition it works, but there was an additional bug related to the third point);
3. when I choose 2 or 1 item per frame - the last slide is shown incorrectly. 

Tests are passed. But I don't like the result and want to improve it.

### CODE REVIEW

**Comment by ArtemZakhar** [comment]
finally make it work correctly!

**Review by metrakonon — APPROVED** [review]
Chill task) Great job! :+1:

**Comment by ArtemZakhar** [comment]
> Chill task) Great job! 👍

Thank you)

**Review by DanilWeda — APPROVED** [review]
Great. 
Approved. 
Thanks)

**Pull request closed without merging**
